<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seeds every configurable system setting with sensible defaults.
 * Safe to re-run - uses upsert on the unique `key` column.
 *
 * FILE LOCATION: database/seeders/SystemSettingSeeder.php
 *
 * Add to DatabaseSeeder:
 *   $this->call(SystemSettingSeeder::class);
 */
class SystemSettingSeeder extends Seeder
{
    public function run(): void
    {
        $settings = [

            // ═══════════════════════════════════════════════════════════════
            // GROUP: hmo_info - Organisation identity
            // ═══════════════════════════════════════════════════════════════
            [
                'key'           => 'hmo_info.name',
                'label'         => 'HMO Name',
                'description'   => 'Full legal name of the HMO as it appears on all documents and reports.',
                'group'         => 'hmo_info',
                'type'          => 'string',
                'default_value' => 'HMO Management System',
                'unit'          => null,
                'sort_order'    => 1,
            ],
            [
                'key'           => 'hmo_info.short_name',
                'label'         => 'Short Name / Trading Name',
                'description'   => 'Abbreviated name used in UI headers and compact reports.',
                'group'         => 'hmo_info',
                'type'          => 'string',
                'default_value' => 'HMO ERP',
                'unit'          => null,
                'sort_order'    => 2,
            ],
            [
                'key'           => 'hmo_info.hmo_code',
                'label'         => 'NHIA HMO Code',
                'description'   => 'Official code assigned by the National Health Insurance Authority. Included in all regulatory submissions.',
                'group'         => 'hmo_info',
                'type'          => 'string',
                'default_value' => 'HMO-000',
                'unit'          => null,
                'sort_order'    => 3,
            ],
            [
                'key'           => 'hmo_info.rc_number',
                'label'         => 'RC Number (CAC)',
                'description'   => 'Corporate Affairs Commission registration number.',
                'group'         => 'hmo_info',
                'type'          => 'string',
                'default_value' => '',
                'unit'          => null,
                'sort_order'    => 4,
            ],
            [
                'key'           => 'hmo_info.address',
                'label'         => 'Head Office Address',
                'description'   => 'Full street address used on letters, invoices, and remittance advice.',
                'group'         => 'hmo_info',
                'type'          => 'string',
                'default_value' => '',
                'unit'          => null,
                'sort_order'    => 5,
            ],
            [
                'key'           => 'hmo_info.city',
                'label'         => 'City',
                'group'         => 'hmo_info',
                'type'          => 'string',
                'default_value' => 'Abuja',
                'unit'          => null,
                'sort_order'    => 6,
            ],
            [
                'key'           => 'hmo_info.state',
                'label'         => 'State',
                'group'         => 'hmo_info',
                'type'          => 'string',
                'default_value' => 'FCT Abuja',
                'unit'          => null,
                'sort_order'    => 7,
            ],
            [
                'key'           => 'hmo_info.phone',
                'label'         => 'Main Phone Number',
                'description'   => 'Customer-facing helpline number. Shown in member portal and on printed materials.',
                'group'         => 'hmo_info',
                'type'          => 'string',
                'default_value' => '',
                'unit'          => null,
                'sort_order'    => 8,
            ],
            [
                'key'           => 'hmo_info.email',
                'label'         => 'Main Email Address',
                'description'   => 'General enquiries email. Shown on portal and documents.',
                'group'         => 'hmo_info',
                'type'          => 'string',
                'default_value' => '',
                'unit'          => null,
                'sort_order'    => 9,
            ],
            [
                'key'           => 'hmo_info.website',
                'label'         => 'Website URL',
                'group'         => 'hmo_info',
                'type'          => 'string',
                'default_value' => '',
                'unit'          => null,
                'sort_order'    => 10,
            ],
            [
                'key'           => 'hmo_info.currency_code',
                'label'         => 'Currency Code',
                'description'   => 'ISO 4217 currency code used throughout the system (e.g. NGN, USD, GHS).',
                'group'         => 'hmo_info',
                'type'          => 'string',
                'default_value' => 'NGN',
                'unit'          => null,
                'sort_order'    => 11,
            ],
            [
                'key'           => 'hmo_info.currency_symbol',
                'label'         => 'Currency Symbol',
                'description'   => 'Symbol displayed next to monetary amounts (e.g. ₦, $, ¢, GH₵).',
                'group'         => 'hmo_info',
                'type'          => 'string',
                'default_value' => '₦',
                'unit'          => null,
                'sort_order'    => 12,
            ],
            [
                'key'           => 'hmo_info.locale',
                'label'         => 'Number Formatting Locale',
                'description'   => 'BCP 47 locale tag used for number and currency formatting (e.g. en-NG, en-GH, en-US).',
                'group'         => 'hmo_info',
                'type'          => 'string',
                'default_value' => 'en-NG',
                'unit'          => null,
                'sort_order'    => 13,
            ],
            [
                'key'           => 'hmo_info.enrollee_id_prefix',
                'label'         => 'Enrollee ID Prefix',
                'description'   => 'Prefix for auto-generated member numbers, e.g. "HMO" → HMO-2024-000001.',
                'group'         => 'hmo_info',
                'type'          => 'string',
                'default_value' => 'HMO',
                'unit'          => null,
                'sort_order'    => 14,
            ],
            [
                'key'           => 'hmo_info.nhia_submission_email',
                'label'         => 'NHIA Submission Email',
                'description'   => 'Email address to CC when regulatory reports are generated.',
                'group'         => 'hmo_info',
                'type'          => 'string',
                'default_value' => '',
                'unit'          => null,
                'sort_order'    => 15,
            ],

            // ═══════════════════════════════════════════════════════════════
            // GROUP: financial - Amounts, rates, thresholds
            // ═══════════════════════════════════════════════════════════════
            [
                'key'              => 'financial.vat_rate',
                'label'            => 'VAT Rate',
                'description'      => 'Applied to corporate invoices when no explicit rate is provided.',
                'group'            => 'financial',
                'type'             => 'decimal',
                'default_value'    => '7.5',
                'unit'             => '%',
                'validation_rules' => ['min' => 0, 'max' => 50],
                'sort_order'       => 1,
            ],
            [
                'key'              => 'financial.claim_escalation_amount',
                'label'            => 'Claim Supervisor Escalation Threshold',
                'description'      => 'Claims above this amount are automatically routed for supervisor review regardless of type.',
                'group'            => 'financial',
                'type'             => 'integer',
                'default_value'    => '500000',
                'unit'             => 'currency',
                'validation_rules' => ['min' => 0],
                'sort_order'       => 2,
            ],
            [
                'key'              => 'financial.pa_md_threshold',
                'label'            => 'Pre-Auth Medical Director Threshold',
                'description'      => 'Pre-authorisations with estimated amount ≥ this value require Medical Director sign-off.',
                'group'            => 'financial',
                'type'             => 'integer',
                'default_value'    => '500000',
                'unit'             => 'currency',
                'validation_rules' => ['min' => 0],
                'sort_order'       => 3,
            ],
            [
                'key'              => 'financial.pa_ceo_threshold',
                'label'            => 'Pre-Auth CEO / Executive Threshold',
                'description'      => 'Pre-authorisations with estimated amount ≥ this value require CEO / executive sign-off.',
                'group'            => 'financial',
                'type'             => 'integer',
                'default_value'    => '2000000',
                'unit'             => 'currency',
                'validation_rules' => ['min' => 0],
                'sort_order'       => 4,
            ],
            [
                'key'              => 'financial.ai_high_value_threshold',
                'label'            => 'AI High-Value Claim Threshold',
                'description'      => 'Claims above this amount are sent to the medical review queue by the AI triage engine.',
                'group'            => 'financial',
                'type'             => 'integer',
                'default_value'    => '500000',
                'unit'             => 'currency',
                'validation_rules' => ['min' => 0],
                'sort_order'       => 5,
            ],
            [
                'key'              => 'financial.max_dependents',
                'label'            => 'Default Maximum Dependents',
                'description'      => 'Default cap on dependents per principal enrollee. Individual plans may override this.',
                'group'            => 'financial',
                'type'             => 'integer',
                'default_value'    => '4',
                'unit'             => 'persons',
                'validation_rules' => ['min' => 0, 'max' => 10],
                'sort_order'       => 6,
            ],
            [
                'key'              => 'financial.claim_submission_deadline_days',
                'label'            => 'Claim Submission Deadline',
                'description'      => 'Number of days after service date within which a claim must be submitted.',
                'group'            => 'financial',
                'type'             => 'integer',
                'default_value'    => '90',
                'unit'             => 'days',
                'validation_rules' => ['min' => 1, 'max' => 365],
                'sort_order'       => 7,
            ],
            [
                'key'              => 'financial.pa_default_validity_days',
                'label'            => 'Default Pre-Auth Validity',
                'description'      => 'Number of days an approved pre-authorisation remains valid (used when no specific value is entered).',
                'group'            => 'financial',
                'type'             => 'integer',
                'default_value'    => '30',
                'unit'             => 'days',
                'validation_rules' => ['min' => 1, 'max' => 365],
                'sort_order'       => 8,
            ],
            [
                'key'              => 'financial.contract_expiry_warning_days',
                'label'            => 'HCP Contract Expiry Warning',
                'description'      => 'Flag HCP contracts as "expiring soon" this many days before their end date.',
                'group'            => 'financial',
                'type'             => 'integer',
                'default_value'    => '30',
                'unit'             => 'days',
                'validation_rules' => ['min' => 1, 'max' => 180],
                'sort_order'       => 9,
            ],
            [
                'key'              => 'financial.benefit_utilisation_warning_pct',
                'label'            => 'Benefit Utilisation Warning Threshold',
                'description'      => 'Notify corporate HR when an enrollee has used this percentage of their annual benefit.',
                'group'            => 'financial',
                'type'             => 'integer',
                'default_value'    => '80',
                'unit'             => '%',
                'validation_rules' => ['min' => 1, 'max' => 100],
                'sort_order'       => 10,
            ],
            [
                'key'              => 'financial.invoice_due_days',
                'label'            => 'Default Invoice Payment Terms',
                'description'      => 'Number of days after issue date before a corporate invoice is considered due.',
                'group'            => 'financial',
                'type'             => 'integer',
                'default_value'    => '30',
                'unit'             => 'days',
                'validation_rules' => ['min' => 1, 'max' => 120],
                'sort_order'       => 11,
            ],

            // ═══════════════════════════════════════════════════════════════
            // GROUP: sla - Per-claim-type processing targets (business days)
            // ═══════════════════════════════════════════════════════════════
            [
                'key'              => 'sla.emergency',
                'label'            => 'Emergency Claim SLA',
                'description'      => 'Maximum business days to process an emergency claim.',
                'group'            => 'sla',
                'type'             => 'integer',
                'default_value'    => '2',
                'unit'             => 'days',
                'validation_rules' => ['min' => 1, 'max' => 30],
                'sort_order'       => 1,
            ],
            [
                'key'              => 'sla.outpatient',
                'label'            => 'Outpatient Claim SLA',
                'group'            => 'sla',
                'type'             => 'integer',
                'default_value'    => '5',
                'unit'             => 'days',
                'validation_rules' => ['min' => 1, 'max' => 30],
                'sort_order'       => 2,
            ],
            [
                'key'              => 'sla.inpatient',
                'label'            => 'Inpatient Claim SLA',
                'group'            => 'sla',
                'type'             => 'integer',
                'default_value'    => '10',
                'unit'             => 'days',
                'validation_rules' => ['min' => 1, 'max' => 30],
                'sort_order'       => 3,
            ],
            [
                'key'              => 'sla.surgery',
                'label'            => 'Surgery Claim SLA',
                'group'            => 'sla',
                'type'             => 'integer',
                'default_value'    => '10',
                'unit'             => 'days',
                'validation_rules' => ['min' => 1, 'max' => 30],
                'sort_order'       => 4,
            ],
            [
                'key'              => 'sla.maternity',
                'label'            => 'Maternity Claim SLA',
                'group'            => 'sla',
                'type'             => 'integer',
                'default_value'    => '10',
                'unit'             => 'days',
                'validation_rules' => ['min' => 1, 'max' => 30],
                'sort_order'       => 5,
            ],
            [
                'key'              => 'sla.dental',
                'label'            => 'Dental Claim SLA',
                'group'            => 'sla',
                'type'             => 'integer',
                'default_value'    => '5',
                'unit'             => 'days',
                'validation_rules' => ['min' => 1, 'max' => 30],
                'sort_order'       => 6,
            ],
            [
                'key'              => 'sla.optical',
                'label'            => 'Optical Claim SLA',
                'group'            => 'sla',
                'type'             => 'integer',
                'default_value'    => '5',
                'unit'             => 'days',
                'validation_rules' => ['min' => 1, 'max' => 30],
                'sort_order'       => 7,
            ],
            [
                'key'              => 'sla.laboratory',
                'label'            => 'Laboratory Claim SLA',
                'group'            => 'sla',
                'type'             => 'integer',
                'default_value'    => '5',
                'unit'             => 'days',
                'validation_rules' => ['min' => 1, 'max' => 30],
                'sort_order'       => 8,
            ],
            [
                'key'              => 'sla.radiology',
                'label'            => 'Radiology Claim SLA',
                'group'            => 'sla',
                'type'             => 'integer',
                'default_value'    => '7',
                'unit'             => 'days',
                'validation_rules' => ['min' => 1, 'max' => 30],
                'sort_order'       => 9,
            ],
            [
                'key'              => 'sla.drug_refill',
                'label'            => 'Drug Refill Claim SLA',
                'group'            => 'sla',
                'type'             => 'integer',
                'default_value'    => '5',
                'unit'             => 'days',
                'validation_rules' => ['min' => 1, 'max' => 30],
                'sort_order'       => 10,
            ],

            // ═══════════════════════════════════════════════════════════════
            // GROUP: pre_auth - PA TAT (Turn-Around-Time) thresholds
            // ═══════════════════════════════════════════════════════════════
            [
                'key'              => 'pre_auth.standard_warn_minutes',
                'label'            => 'Standard PA - Warning at (minutes)',
                'description'      => 'A standard PA pending this long shows a yellow warning.',
                'group'            => 'pre_auth',
                'type'             => 'integer',
                'default_value'    => '15',
                'unit'             => 'minutes',
                'validation_rules' => ['min' => 1],
                'sort_order'       => 1,
            ],
            [
                'key'              => 'pre_auth.standard_limit_minutes',
                'label'            => 'Standard PA - Breach at (minutes)',
                'description'      => 'A standard PA pending this long is marked as overdue.',
                'group'            => 'pre_auth',
                'type'             => 'integer',
                'default_value'    => '30',
                'unit'             => 'minutes',
                'validation_rules' => ['min' => 1],
                'sort_order'       => 2,
            ],
            [
                'key'              => 'pre_auth.urgent_warn_minutes',
                'label'            => 'Urgent PA - Warning at (minutes)',
                'group'            => 'pre_auth',
                'type'             => 'integer',
                'default_value'    => '30',
                'unit'             => 'minutes',
                'validation_rules' => ['min' => 1],
                'sort_order'       => 3,
            ],
            [
                'key'              => 'pre_auth.urgent_limit_minutes',
                'label'            => 'Urgent PA - Breach at (minutes)',
                'group'            => 'pre_auth',
                'type'             => 'integer',
                'default_value'    => '60',
                'unit'             => 'minutes',
                'validation_rules' => ['min' => 1],
                'sort_order'       => 4,
            ],
            [
                'key'              => 'pre_auth.emergency_warn_minutes',
                'label'            => 'Emergency PA - Warning at (minutes)',
                'description'      => 'Default is 720 minutes (12 hours).',
                'group'            => 'pre_auth',
                'type'             => 'integer',
                'default_value'    => '720',
                'unit'             => 'minutes',
                'validation_rules' => ['min' => 1],
                'sort_order'       => 5,
            ],
            [
                'key'              => 'pre_auth.emergency_limit_minutes',
                'label'            => 'Emergency PA - Breach at (minutes)',
                'description'      => 'Default is 1440 minutes (24 hours).',
                'group'            => 'pre_auth',
                'type'             => 'integer',
                'default_value'    => '1440',
                'unit'             => 'minutes',
                'validation_rules' => ['min' => 1],
                'sort_order'       => 6,
            ],

            // ═══════════════════════════════════════════════════════════════
            // GROUP: fraud - Fraud detection thresholds and score weights
            // ═══════════════════════════════════════════════════════════════
            [
                'key'              => 'fraud.auto_quarantine_threshold',
                'label'            => 'Auto-Escalate Risk Score',
                'description'      => 'Claims with risk score ≥ this are automatically routed to supervisor review queue.',
                'group'            => 'fraud',
                'type'             => 'integer',
                'default_value'    => '70',
                'unit'             => '/100',
                'validation_rules' => ['min' => 1, 'max' => 100],
                'sort_order'       => 1,
            ],
            [
                'key'              => 'fraud.auto_reject_threshold',
                'label'            => 'Auto-Reject Risk Score',
                'description'      => 'Claims with risk score ≥ this are rejected without human review. Set high (95+) to prevent false positives.',
                'group'            => 'fraud',
                'type'             => 'integer',
                'default_value'    => '95',
                'unit'             => '/100',
                'validation_rules' => ['min' => 1, 'max' => 100],
                'sort_order'       => 2,
            ],
            [
                'key'              => 'fraud.critical_notification_threshold',
                'label'            => 'Critical Fraud Notification Score',
                'description'      => 'Risk scores at or above this trigger a "critical" severity notification (vs. "warning").',
                'group'            => 'fraud',
                'type'             => 'integer',
                'default_value'    => '90',
                'unit'             => '/100',
                'validation_rules' => ['min' => 1, 'max' => 100],
                'sort_order'       => 3,
            ],
            [
                'key'              => 'fraud.duplicate_window_days',
                'label'            => 'Duplicate Detection Window',
                'description'      => 'Claims for the same service from the same HCP for the same enrollee within this window are flagged as potential duplicates.',
                'group'            => 'fraud',
                'type'             => 'integer',
                'default_value'    => '30',
                'unit'             => 'days',
                'validation_rules' => ['min' => 1, 'max' => 365],
                'sort_order'       => 4,
            ],
            [
                'key'              => 'fraud.frequency_threshold_monthly',
                'label'            => 'HCP Frequency Anomaly Threshold',
                'description'      => 'Max number of claims allowed from the same HCP for the same enrollee in one calendar month before a frequency anomaly flag is raised.',
                'group'            => 'fraud',
                'type'             => 'integer',
                'default_value'    => '4',
                'unit'             => 'claims/month',
                'validation_rules' => ['min' => 1, 'max' => 50],
                'sort_order'       => 5,
            ],
            [
                'key'              => 'fraud.cost_spike_multiplier',
                'label'            => 'Cost Spike Multiplier',
                'description'      => 'If a claim item price exceeds the agreed tariff by this multiple, a cost-spike flag is raised.',
                'group'            => 'fraud',
                'type'             => 'decimal',
                'default_value'    => '1.5',
                'unit'             => '× tariff',
                'validation_rules' => ['min' => 1, 'max' => 10],
                'sort_order'       => 6,
            ],
            [
                'key'              => 'fraud.high_cost_enrollee_threshold',
                'label'            => 'High-Cost Enrollee Annual Threshold',
                'description'      => 'Annual claim spend per enrollee above this triggers a high-cost flag for fraud review.',
                'group'            => 'fraud',
                'type'             => 'integer',
                'default_value'    => '2000000',
                'unit'             => 'currency',
                'validation_rules' => ['min' => 0],
                'sort_order'       => 7,
            ],
            [
                'key'              => 'fraud.provider_baseline_months',
                'label'            => 'Provider Baseline Period',
                'description'      => 'Number of months of claim history used to build the provider average for deviation scoring.',
                'group'            => 'fraud',
                'type'             => 'integer',
                'default_value'    => '6',
                'unit'             => 'months',
                'validation_rules' => ['min' => 1, 'max' => 24],
                'sort_order'       => 8,
            ],
            [
                'key'              => 'fraud.min_claims_for_baseline',
                'label'            => 'Minimum Claims for Baseline',
                'description'      => 'Minimum number of historical claims needed before provider deviation scoring is considered reliable.',
                'group'            => 'fraud',
                'type'             => 'integer',
                'default_value'    => '10',
                'unit'             => 'claims',
                'validation_rules' => ['min' => 1, 'max' => 100],
                'sort_order'       => 9,
            ],
            // Score weights stored individually so each has its own label/description
            [
                'key'              => 'fraud.weight_duplicate_claim',
                'label'            => 'Score Weight - Duplicate Claim',
                'group'            => 'fraud',
                'type'             => 'integer',
                'default_value'    => '40',
                'unit'             => 'pts',
                'validation_rules' => ['min' => 0, 'max' => 100],
                'sort_order'       => 10,
            ],
            [
                'key'              => 'fraud.weight_tariff_mismatch',
                'label'            => 'Score Weight - Tariff Mismatch',
                'group'            => 'fraud',
                'type'             => 'integer',
                'default_value'    => '25',
                'unit'             => 'pts',
                'validation_rules' => ['min' => 0, 'max' => 100],
                'sort_order'       => 11,
            ],
            [
                'key'              => 'fraud.weight_over_benefit_limit',
                'label'            => 'Score Weight - Over Benefit Limit',
                'group'            => 'fraud',
                'type'             => 'integer',
                'default_value'    => '20',
                'unit'             => 'pts',
                'validation_rules' => ['min' => 0, 'max' => 100],
                'sort_order'       => 12,
            ],
            [
                'key'              => 'fraud.weight_frequency_anomaly',
                'label'            => 'Score Weight - Frequency Anomaly',
                'group'            => 'fraud',
                'type'             => 'integer',
                'default_value'    => '20',
                'unit'             => 'pts',
                'validation_rules' => ['min' => 0, 'max' => 100],
                'sort_order'       => 13,
            ],
            [
                'key'              => 'fraud.weight_cost_spike',
                'label'            => 'Score Weight - Cost Spike',
                'group'            => 'fraud',
                'type'             => 'integer',
                'default_value'    => '25',
                'unit'             => 'pts',
                'validation_rules' => ['min' => 0, 'max' => 100],
                'sort_order'       => 14,
            ],
            [
                'key'              => 'fraud.weight_pattern_deviation',
                'label'            => 'Score Weight - Pattern Deviation',
                'group'            => 'fraud',
                'type'             => 'integer',
                'default_value'    => '10',
                'unit'             => 'pts',
                'validation_rules' => ['min' => 0, 'max' => 100],
                'sort_order'       => 15,
            ],
            [
                'key'              => 'fraud.weight_pre_auth_missing',
                'label'            => 'Score Weight - Pre-Auth Missing',
                'group'            => 'fraud',
                'type'             => 'integer',
                'default_value'    => '15',
                'unit'             => 'pts',
                'validation_rules' => ['min' => 0, 'max' => 100],
                'sort_order'       => 16,
            ],

            // ═══════════════════════════════════════════════════════════════
            // GROUP: notifications - Alert trigger thresholds
            // ═══════════════════════════════════════════════════════════════
            [
                'key'              => 'notifications.compliance_critical_days',
                'label'            => 'Compliance Filing - Critical Alert Window',
                'description'      => 'Filings due within this many days trigger a "critical" severity notification.',
                'group'            => 'notifications',
                'type'             => 'integer',
                'default_value'    => '3',
                'unit'             => 'days',
                'validation_rules' => ['min' => 1, 'max' => 30],
                'sort_order'       => 1,
            ],
            [
                'key'              => 'notifications.compliance_warning_days',
                'label'            => 'Compliance Filing - Warning Alert Window',
                'description'      => 'Filings due within this many days (but after the critical window) trigger a "warning" notification.',
                'group'            => 'notifications',
                'type'             => 'integer',
                'default_value'    => '7',
                'unit'             => 'days',
                'validation_rules' => ['min' => 1, 'max' => 60],
                'sort_order'       => 2,
            ],
            [
                'key'              => 'notifications.benefit_alert_pct',
                'label'            => 'Enrollee Benefit Alert Threshold',
                'description'      => 'Send a benefit utilisation alert when an enrollee reaches this percentage of their annual limit.',
                'group'            => 'notifications',
                'type'             => 'integer',
                'default_value'    => '80',
                'unit'             => '%',
                'validation_rules' => ['min' => 1, 'max' => 100],
                'sort_order'       => 3,
            ],

            // ═══════════════════════════════════════════════════════════════
            // GROUP: operational - System behaviour settings
            // ═══════════════════════════════════════════════════════════════
            [
                'key'              => 'operational.token_lifetime_hours',
                'label'            => 'Session Token Lifetime',
                'description'      => 'How long a Sanctum API token stays valid after issuance. Users are logged out after this period of inactivity.',
                'group'            => 'operational',
                'type'             => 'integer',
                'default_value'    => '12',
                'unit'             => 'hours',
                'validation_rules' => ['min' => 1, 'max' => 168],
                'sort_order'       => 1,
            ],
            [
                'key'              => 'operational.dashboard_cache_minutes',
                'label'            => 'Dashboard Cache Duration',
                'description'      => 'How long dashboard statistics are cached before a fresh database query runs.',
                'group'            => 'operational',
                'type'             => 'integer',
                'default_value'    => '5',
                'unit'             => 'minutes',
                'validation_rules' => ['min' => 0, 'max' => 60],
                'sort_order'       => 2,
            ],
            [
                'key'              => 'operational.bulk_import_max_mb',
                'label'            => 'Bulk Import Max File Size',
                'description'      => 'Maximum file size for spreadsheet bulk imports.',
                'group'            => 'operational',
                'type'             => 'integer',
                'default_value'    => '10',
                'unit'             => 'MB',
                'validation_rules' => ['min' => 1, 'max' => 100],
                'sort_order'       => 3,
            ],
            [
                'key'              => 'operational.pa_retrospective_emergency_hours',
                'label'            => 'Emergency Retrospective PA Window',
                'description'      => 'Emergency pre-auths older than this without a decision are flagged as overdue.',
                'group'            => 'operational',
                'type'             => 'integer',
                'default_value'    => '24',
                'unit'             => 'hours',
                'validation_rules' => ['min' => 1, 'max' => 72],
                'sort_order'       => 4,
            ],
        ];

        // Upsert - safe to re-run; only updates non-value columns on conflict
        // (never overwrites a live value that an admin has changed)
        foreach ($settings as $setting) {
            DB::table('system_settings')->upsert(
                array_merge($setting, [
                    'value'      => null,                          // null = "use default"
                    'is_hidden'  => $setting['is_hidden']  ?? false,
                    'is_readonly'=> $setting['is_readonly'] ?? false,
                    'created_at' => now(),
                    'updated_at' => now(),
                    'validation_rules' => isset($setting['validation_rules'])
                        ? json_encode($setting['validation_rules'])
                        : null,
                ]),
                ['key'],                                           // conflict on key
                ['label', 'description', 'group', 'type',         // update metadata only
                 'default_value', 'unit', 'validation_rules',
                 'sort_order', 'updated_at'],
            );
        }
    }
}