/**
 * FILE LOCATION: resources/js/pages/finance/CapitationDetailPage.jsx
 * ROUTE:         /finance/capitation/:id
 * PERMISSION:    finance.capitation
 *
 * Shows a single capitation run in full detail:
 *   - Run header (period, status, totals, variance vs prior month)
 *   - Per-HCP reconciliation table (principals, dependants, rates, amounts)
 *   - Adjustment editing for draft runs
 *   - Approve action (creates payment batch)
 */

import React, { useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { toast } from 'react-toastify';
import {
    ArrowLeft, CheckCircle, TrendingUp, TrendingDown,
    Users, Building2, DollarSign, Edit2, AlertTriangle,
    FileText, Info, ChevronRight, Minus,
} from 'lucide-react';
import {
    fetchCapitationRun, approveCapitationRun, adjustCapitationRecord,
} from '../../api/index';
import {
    PageHeader, LoadingSpinner, ErrorAlert,
} from '../../components/ui/index';
import { formatCurrency, formatDate } from '../../utils/format';
import { useAuth } from '../../contexts/AuthContext';

// ─── Status config ───────────────────────────────────────────────────────────
const RUN_STATUS = {
    draft:    { label: 'Draft - Pending Approval',  color: '#6b7280', bg: '#f3f4f6', icon: FileText   },
    approved: { label: 'Approved - Batch Created',  color: '#0f4c81', bg: '#e8f0fe', icon: CheckCircle },
    paid:     { label: 'Paid',                       color: '#137333', bg: '#e6f4ea', icon: CheckCircle },
};

export default function CapitationDetailPage() {
    const { id } = useParams();
    const navigate = useNavigate();
    const qc = useQueryClient();
    const { hasPermission } = useAuth();
    const canManage = hasPermission('finance.capitation');

    const [adjusting, setAdjusting] = useState(null); // record to adjust

    const { data, isLoading, isError, refetch } = useQuery({
        queryKey: ['capitation-run', id],
        queryFn:  () => fetchCapitationRun(id),
    });

    const approveMutation = useMutation({
        mutationFn: () => approveCapitationRun(id),
        onSuccess: (res) => {
            const d = res.data?.data ?? res.data;
            toast.success(`Run approved. Payment batch ${d.batch_number} created.`);
            qc.invalidateQueries({ queryKey: ['capitation-run', id] });
            qc.invalidateQueries({ queryKey: ['capitation-runs'] });
            qc.invalidateQueries({ queryKey: ['capitation-summary'] });
        },
        onError: (err) => toast.error(err.response?.data?.message ?? 'Approval failed.'),
    });

    if (isLoading) return (
        <div className="d-flex justify-content-center py-5"><LoadingSpinner /></div>
    );
    if (isError) return (
        <ErrorAlert message="Failed to load capitation run." onRetry={refetch} />
    );

    const run     = data?.data ?? data;
    const st      = RUN_STATUS[run.status] ?? RUN_STATUS.draft;
    const isDraft = run.status === 'draft';

    const varPositive = run.member_variance > 0;
    const varZero     = run.member_variance === 0;

    return (
        <div>
            {/* Header */}
            <div className="d-flex align-items-start gap-3 mb-4">
                <button
                    className="btn btn-sm btn-outline-secondary d-flex align-items-center gap-1"
                    onClick={() => navigate('/finance/capitation')}
                >
                    <ArrowLeft size={14} /> Back
                </button>
                <div className="flex-grow-1">
                    <div className="d-flex align-items-center gap-3 flex-wrap">
                        <h4 className="mb-0 fw-bold" style={{ color: '#111' }}>
                            Capitation Run - {run.period_label}
                        </h4>
                        <span style={{
                            padding: '4px 12px', borderRadius: 12, fontSize: 12, fontWeight: 600,
                            color: st.color, background: st.bg,
                        }}>
                            {st.label}
                        </span>
                    </div>
                    <div className="text-muted mt-1" style={{ fontSize: 13 }}>
                        Generated by {run.generated_by_name} on {formatDate(run.created_at)}
                        {run.approved_by_name && ` · Approved by ${run.approved_by_name} on ${formatDate(run.approved_at)}`}
                    </div>
                </div>

                {/* Approve button */}
                {isDraft && canManage && (
                    <button
                        className="btn btn-success btn-sm d-flex align-items-center gap-2 flex-shrink-0"
                        disabled={approveMutation.isPending || run.total_amount <= 0}
                        onClick={() => {
                            if (window.confirm(`Approve this run for ${formatCurrency(run.total_amount)}? A payment batch will be created.`)) {
                                approveMutation.mutate();
                            }
                        }}
                    >
                        {approveMutation.isPending
                            ? <span className="spinner-border spinner-border-sm" />
                            : <CheckCircle size={15} />
                        }
                        Approve & Create Batch
                    </button>
                )}

                {/* Batch link */}
                {run.batch_number && (
                    <button
                        className="btn btn-outline-primary btn-sm d-flex align-items-center gap-2"
                        onClick={() => navigate(`/finance/batches/${run.payment_batch_id}`)}
                    >
                        <FileText size={14} /> {run.batch_number}
                        <ChevronRight size={14} />
                    </button>
                )}
            </div>

            {/* KPI row */}
            <div className="row g-3 mb-4">
                <KpiCard
                    label="Total Payable"
                    value={formatCurrency(run.total_amount)}
                    icon={DollarSign}
                    color="#0f4c81"
                    bg="#e8f0fe"
                    sub={isDraft ? 'Draft - subject to change' : 'Finalised'}
                />
                <KpiCard
                    label="HCPs Included"
                    value={run.total_hcp_count?.toLocaleString()}
                    icon={Building2}
                    color="#7c3aed"
                    bg="#f5f3ff"
                    sub="Healthcare providers"
                />
                <KpiCard
                    label="Total Members"
                    value={run.total_member_count?.toLocaleString()}
                    icon={Users}
                    color="#137333"
                    bg="#e6f4ea"
                    sub={`${run.total_principal_count ?? 0} principals + ${run.total_dependent_count ?? 0} dependants`}
                />
                <KpiCard
                    label="Variance vs Prior Month"
                    value={varZero ? '-' : `${varPositive ? '+' : ''}${run.member_variance}`}
                    icon={varPositive ? TrendingUp : varZero ? Minus : TrendingDown}
                    color={varZero ? '#6b7280' : varPositive ? '#137333' : '#c5221f'}
                    bg={varZero ? '#f3f4f6' : varPositive ? '#e6f4ea' : '#fce8e6'}
                    sub={varZero ? 'No change from last month' : varPositive ? 'Members increased' : 'Members decreased'}
                />
            </div>

            {/* Reconciliation note for draft */}
            {isDraft && (
                <div className="alert alert-info d-flex align-items-start gap-2 mb-4 py-2" style={{ fontSize: 13 }}>
                    <Info size={15} className="flex-shrink-0 mt-1" />
                    <span>
                        This run is in <strong>draft</strong>. Review the headcount figures below.
                        You can manually adjust individual HCP lines to correct for mid-month
                        transfers or other exceptions. When ready, click <strong>Approve & Create Batch</strong>.
                    </span>
                </div>
            )}

            {/* Reconciliation Table */}
            <div className="card border-0 shadow-sm" style={{ borderRadius: 12 }}>
                <div className="card-header bg-white py-3 border-bottom">
                    <div className="fw-semibold" style={{ fontSize: 14 }}>
                        Headcount Reconciliation - {run.period_label}
                    </div>
                    <div className="text-muted" style={{ fontSize: 12 }}>
                        Showing all HCPs included in this run. Variance column compares to the previous approved run.
                    </div>
                </div>

                <div className="table-responsive">
                    <table className="table table-hover align-middle mb-0" style={{ fontSize: 13 }}>
                        <thead style={{ background: '#f8fafc' }}>
                            <tr>
                                <th className="ps-4" style={{ fontWeight: 600, color: '#374151', width: '22%' }}>HCP</th>
                                <th style={{ fontWeight: 600, color: '#374151' }}>Tier</th>
                                <th className="text-end" style={{ fontWeight: 600, color: '#374151' }}>Principals</th>
                                <th className="text-end" style={{ fontWeight: 600, color: '#374151' }}>Dependants</th>
                                <th className="text-end" style={{ fontWeight: 600, color: '#374151' }}>Total</th>
                                <th className="text-end" style={{ fontWeight: 600, color: '#374151' }}>Variance</th>
                                <th className="text-end" style={{ fontWeight: 600, color: '#374151' }}>P Rate</th>
                                <th className="text-end" style={{ fontWeight: 600, color: '#374151' }}>D Rate</th>
                                <th className="text-end" style={{ fontWeight: 600, color: '#374151' }}>Amount</th>
                                <th className="text-end" style={{ fontWeight: 600, color: '#374151' }}>Adjustment</th>
                                <th className="text-end" style={{ fontWeight: 600, color: '#374151' }}>Total Payable</th>
                                {isDraft && canManage && <th></th>}
                            </tr>
                        </thead>
                        <tbody>
                            {(run.records ?? []).map(rec => {
                                const rv = rec.member_variance;
                                const adjTotal = (rec.total_amount ?? 0) + (rec.adjustment_amount ?? 0);

                                return (
                                    <tr key={rec.id}>
                                        <td className="ps-4">
                                            <div style={{ fontWeight: 600, color: '#111' }}>
                                                {rec.hcp_name}
                                            </div>
                                            <div style={{ fontSize: 11, color: '#6b7280', fontFamily: 'monospace' }}>
                                                {rec.hcp_code ?? rec.hcp_tier}
                                            </div>
                                        </td>
                                        <td>
                                            <TierBadge tier={rec.hcp_tier} />
                                        </td>
                                        <td className="text-end font-monospace">{rec.principal_count}</td>
                                        <td className="text-end font-monospace">{rec.dependent_count}</td>
                                        <td className="text-end font-monospace fw-semibold">{rec.enrolled_member_count}</td>
                                        <td className="text-end">
                                            <VariancePill variance={rv} />
                                        </td>
                                        <td className="text-end" style={{ color: '#374151' }}>
                                            {formatCurrency(rec.rate_per_member)}
                                        </td>
                                        <td className="text-end" style={{ color: '#374151' }}>
                                            {formatCurrency(rec.rate_per_dependent ?? rec.rate_per_member)}
                                        </td>
                                        <td className="text-end font-monospace">
                                            {formatCurrency(rec.total_amount)}
                                        </td>
                                        <td className="text-end">
                                            {rec.adjustment_amount !== 0 ? (
                                                <span
                                                    style={{ color: rec.adjustment_amount > 0 ? '#137333' : '#c5221f', fontWeight: 600, fontSize: 12 }}
                                                    title={rec.adjustment_note}
                                                >
                                                    {rec.adjustment_amount > 0 ? '+' : ''}
                                                    {formatCurrency(rec.adjustment_amount)}
                                                </span>
                                            ) : (
                                                <span className="text-muted">-</span>
                                            )}
                                        </td>
                                        <td className="text-end">
                                            <strong style={{ color: '#0f4c81' }}>
                                                {formatCurrency(adjTotal)}
                                            </strong>
                                        </td>
                                        {isDraft && canManage && (
                                            <td>
                                                <button
                                                    className="btn btn-sm btn-outline-secondary py-0 px-2"
                                                    title="Adjust this record"
                                                    onClick={() => setAdjusting(rec)}
                                                >
                                                    <Edit2 size={12} />
                                                </button>
                                            </td>
                                        )}
                                    </tr>
                                );
                            })}
                        </tbody>

                        {/* Totals footer */}
                        <tfoot style={{ background: '#f8fafc', borderTop: '2px solid #e5e7eb' }}>
                            <tr>
                                <td className="ps-4 fw-bold" colSpan={4}>Totals</td>
                                <td className="text-end fw-bold font-monospace">
                                    {run.total_member_count?.toLocaleString()}
                                </td>
                                <td className="text-end">
                                    <VariancePill variance={run.member_variance} />
                                </td>
                                <td colSpan={2}></td>
                                <td className="text-end fw-bold font-monospace">
                                    {formatCurrency(run.records?.reduce((s, r) => s + (r.total_amount ?? 0), 0) ?? 0)}
                                </td>
                                <td className="text-end fw-bold font-monospace">
                                    {formatCurrency(run.records?.reduce((s, r) => s + (r.adjustment_amount ?? 0), 0) ?? 0)}
                                </td>
                                <td className="text-end">
                                    <strong style={{ color: '#0f4c81', fontSize: 15 }}>
                                        {formatCurrency(run.total_amount)}
                                    </strong>
                                </td>
                                {isDraft && canManage && <td />}
                            </tr>
                        </tfoot>
                    </table>
                </div>

                {/* Notes */}
                {run.notes && (
                    <div className="card-footer bg-white" style={{ fontSize: 13, color: '#374151' }}>
                        <strong>Notes:</strong> {run.notes}
                    </div>
                )}
            </div>

            {/* Adjust Record Modal */}
            {adjusting && (
                <AdjustRecordModal
                    runId={id}
                    record={adjusting}
                    onClose={() => setAdjusting(null)}
                    onSuccess={() => {
                        qc.invalidateQueries({ queryKey: ['capitation-run', id] });
                        qc.invalidateQueries({ queryKey: ['capitation-summary'] });
                        setAdjusting(null);
                    }}
                />
            )}
        </div>
    );
}

/* ── Sub-components ─────────────────────────────────────────────────────────── */

function KpiCard({ label, value, icon: Icon, color, bg, sub }) {
    return (
        <div className="col-md-3">
            <div className="card border-0 shadow-sm h-100" style={{ borderRadius: 12 }}>
                <div className="card-body d-flex align-items-start gap-3" style={{ padding: '16px 20px' }}>
                    <div style={{
                        width: 42, height: 42, borderRadius: 10,
                        background: bg, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
                    }}>
                        <Icon size={20} color={color} />
                    </div>
                    <div className="overflow-hidden">
                        <div style={{ fontSize: 11, color: '#6b7280', textTransform: 'uppercase', letterSpacing: 0.5 }}>
                            {label}
                        </div>
                        <div style={{ fontSize: 19, fontWeight: 700, color: '#111', lineHeight: 1.2 }}>
                            {value}
                        </div>
                        <div style={{ fontSize: 11, color: '#6b7280', marginTop: 2 }}>{sub}</div>
                    </div>
                </div>
            </div>
        </div>
    );
}

const TIER_STYLE = {
    primary:   { color: '#0f4c81', bg: '#e8f0fe' },
    secondary: { color: '#7c3aed', bg: '#f5f3ff' },
    tertiary:  { color: '#b45309', bg: '#fef3c7' },
};

function TierBadge({ tier }) {
    const s = TIER_STYLE[tier] ?? { color: '#6b7280', bg: '#f3f4f6' };
    return (
        <span style={{
            padding: '2px 8px', borderRadius: 10, fontSize: 11, fontWeight: 600,
            textTransform: 'capitalize', color: s.color, background: s.bg,
        }}>
            {tier ?? '-'}
        </span>
    );
}

function VariancePill({ variance }) {
    if (!variance || variance === 0) return <span className="text-muted font-monospace">-</span>;
    const pos = variance > 0;
    return (
        <span style={{
            display: 'inline-flex', alignItems: 'center', gap: 2,
            color: pos ? '#137333' : '#c5221f', fontWeight: 600, fontSize: 12,
        }}>
            {pos ? <TrendingUp size={11} /> : <TrendingDown size={11} />}
            {pos ? '+' : ''}{variance}
        </span>
    );
}

/* ── Adjust Record Modal ─────────────────────────────────────────────────────── */

function AdjustRecordModal({ runId, record, onClose, onSuccess }) {
    const [form, setForm] = useState({
        principal_count:    record.principal_count,
        dependent_count:    record.dependent_count,
        adjustment_amount:  record.adjustment_amount ?? 0,
        adjustment_note:    record.adjustment_note ?? '',
        notes:              record.notes ?? '',
    });
    const [errors, setErrors] = useState({});

    const mutation = useMutation({
        mutationFn: (payload) => adjustCapitationRecord(runId, record.id, payload),
        onSuccess: () => {
            toast.success('Record adjusted. Run totals updated.');
            onSuccess();
        },
        onError: (err) => {
            toast.error(err.response?.data?.message ?? 'Adjustment failed.');
            if (err.response?.data?.errors) setErrors(err.response.data.errors);
        },
    });

    const projectedPrincipal  = +form.principal_count * record.rate_per_member;
    const projectedDependent  = +form.dependent_count * (record.rate_per_dependent ?? record.rate_per_member);
    const projectedBase       = projectedPrincipal + projectedDependent;
    const projectedTotal      = projectedBase + (+form.adjustment_amount || 0);
    const originalTotal       = (record.total_amount ?? 0) + (record.adjustment_amount ?? 0);
    const delta               = projectedTotal - originalTotal;

    return (
        <div className="modal d-block" style={{ background: 'rgba(0,0,0,0.45)', zIndex: 1055 }}>
            <div className="modal-dialog modal-lg modal-dialog-centered">
                <div className="modal-content">
                    <div className="modal-header">
                        <div>
                            <h5 className="modal-title fw-bold mb-0">
                                Adjust Record - {record.hcp_name}
                            </h5>
                            <div className="text-muted" style={{ fontSize: 12 }}>
                                Current: {record.enrolled_member_count} members · {formatCurrency((record.total_amount ?? 0) + (record.adjustment_amount ?? 0))}
                            </div>
                        </div>
                        <button className="btn-close" onClick={onClose} />
                    </div>

                    <div className="modal-body">
                        <div className="alert alert-warning py-2 mb-3 d-flex align-items-start gap-2" style={{ fontSize: 13 }}>
                            <AlertTriangle size={15} className="flex-shrink-0 mt-1" />
                            <span>
                                Changes here override the system-computed headcount.
                                Use this for mid-month transfers, late registrations, or confirmed data discrepancies.
                                Provide a reason in the Notes field.
                            </span>
                        </div>

                        <div className="row g-3">
                            {/* Counts */}
                            <div className="col-6">
                                <label className="form-label fw-semibold" style={{ fontSize: 13 }}>
                                    Principal Count
                                </label>
                                <input
                                    type="number"
                                    min={0}
                                    className={`form-control form-control-sm ${errors.principal_count ? 'is-invalid' : ''}`}
                                    value={form.principal_count}
                                    onChange={e => setForm(p => ({ ...p, principal_count: e.target.value }))}
                                />
                                {errors.principal_count && <div className="invalid-feedback">{errors.principal_count}</div>}
                                <div className="form-text">System: {record.principal_count}</div>
                            </div>
                            <div className="col-6">
                                <label className="form-label fw-semibold" style={{ fontSize: 13 }}>
                                    Dependant Count
                                </label>
                                <input
                                    type="number"
                                    min={0}
                                    className={`form-control form-control-sm ${errors.dependent_count ? 'is-invalid' : ''}`}
                                    value={form.dependent_count}
                                    onChange={e => setForm(p => ({ ...p, dependent_count: e.target.value }))}
                                />
                                {errors.dependent_count && <div className="invalid-feedback">{errors.dependent_count}</div>}
                                <div className="form-text">System: {record.dependent_count}</div>
                            </div>

                            {/* Adjustment */}
                            <div className="col-6">
                                <label className="form-label fw-semibold" style={{ fontSize: 13 }}>
                                    Manual Adjustment (₦)
                                    <span className="text-muted fw-normal ms-1">+/−</span>
                                </label>
                                <input
                                    type="number"
                                    step="0.01"
                                    className={`form-control form-control-sm ${errors.adjustment_amount ? 'is-invalid' : ''}`}
                                    value={form.adjustment_amount}
                                    onChange={e => setForm(p => ({ ...p, adjustment_amount: e.target.value }))}
                                    placeholder="0.00"
                                />
                                {errors.adjustment_amount && <div className="invalid-feedback">{errors.adjustment_amount}</div>}
                            </div>
                            <div className="col-6">
                                <label className="form-label fw-semibold" style={{ fontSize: 13 }}>
                                    Adjustment Reason <span className="text-danger">*</span>
                                </label>
                                <input
                                    type="text"
                                    className={`form-control form-control-sm ${errors.adjustment_note ? 'is-invalid' : ''}`}
                                    value={form.adjustment_note}
                                    onChange={e => setForm(p => ({ ...p, adjustment_note: e.target.value }))}
                                    placeholder="e.g. 3 mid-month transfers not yet reflected"
                                />
                                {errors.adjustment_note && <div className="invalid-feedback">{errors.adjustment_note}</div>}
                            </div>
                            <div className="col-12">
                                <label className="form-label fw-semibold" style={{ fontSize: 13 }}>
                                    Internal Notes
                                </label>
                                <textarea
                                    className="form-control form-control-sm"
                                    rows={2}
                                    value={form.notes}
                                    onChange={e => setForm(p => ({ ...p, notes: e.target.value }))}
                                    placeholder="Additional context for auditors"
                                />
                            </div>
                        </div>

                        {/* Live projection */}
                        <div className="card mt-3 border-0" style={{ background: '#f8fafc', borderRadius: 10 }}>
                            <div className="card-body py-3 px-4">
                                <div className="fw-semibold mb-2" style={{ fontSize: 13, color: '#374151' }}>
                                    Projected Outcome
                                </div>
                                <div className="row g-2" style={{ fontSize: 13 }}>
                                    {[
                                        { label: 'Principal amount', value: formatCurrency(projectedPrincipal) },
                                        { label: 'Dependant amount', value: formatCurrency(projectedDependent) },
                                        { label: 'Base total',       value: formatCurrency(projectedBase) },
                                        { label: 'Adjustment',       value: formatCurrency(+form.adjustment_amount || 0) },
                                    ].map(row => (
                                        <div key={row.label} className="col-6 d-flex justify-content-between" style={{ color: '#6b7280' }}>
                                            <span>{row.label}</span>
                                            <span className="font-monospace">{row.value}</span>
                                        </div>
                                    ))}
                                    <div className="col-12">
                                        <hr className="my-1" />
                                    </div>
                                    <div className="col-6 d-flex justify-content-between fw-bold">
                                        <span style={{ color: '#111' }}>New total</span>
                                        <span style={{ color: '#0f4c81', fontFamily: 'monospace' }}>{formatCurrency(projectedTotal)}</span>
                                    </div>
                                    <div className="col-6 d-flex justify-content-between">
                                        <span style={{ color: '#6b7280' }}>Change to run total</span>
                                        <span style={{
                                            color: delta === 0 ? '#6b7280' : delta > 0 ? '#137333' : '#c5221f',
                                            fontWeight: 600, fontFamily: 'monospace',
                                        }}>
                                            {delta >= 0 ? '+' : ''}{formatCurrency(delta)}
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div className="modal-footer">
                        <button className="btn btn-outline-secondary btn-sm" onClick={onClose}>
                            Cancel
                        </button>
                        <button
                            className="btn btn-primary btn-sm"
                            disabled={mutation.isPending}
                            onClick={() => mutation.mutate(form)}
                        >
                            {mutation.isPending
                                ? <><span className="spinner-border spinner-border-sm me-1" /> Saving…</>
                                : 'Apply Adjustment'
                            }
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
}