<?php
/**
 * FILE: database/migrations/2025_07_03_000003_create_generated_reports_table.php
 */
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('generated_reports', function (Blueprint $table) {
            $table->id();

            $table->foreignId('generated_by')
                  ->nullable()      // null = auto-generated by scheduler
                  ->constrained('users')
                  ->nullOnDelete();

            $table->enum('report_type', [
                'monthly_claims_returns',
                'capitation_payment_schedule',
                'quarterly_utilisation',
                'ffs_claims_register',
                'annual_report',
                'ffs_remittance_advice',   // to HCP
                'corporate_cost_report',    // to Corporate
            ]);

            // Period this report covers
            $table->string('period');           // "2025-06" | "2025-Q2" | "2025"
            $table->date('period_start');
            $table->date('period_end');

            // For HCP-specific reports (FFS remittance)
            $table->foreignId('hcp_id')
                  ->nullable()
                  ->constrained('health_care_providers')
                  ->nullOnDelete();

            // For corporate-specific reports
            $table->foreignId('corporate_id')
                  ->nullable()
                  ->constrained('corporates')
                  ->nullOnDelete();

            // For FFS remittance - link to payment batch
            $table->foreignId('payment_batch_id')
                  ->nullable()
                  ->constrained('payment_batches')
                  ->nullOnDelete();

            $table->enum('format', ['xlsx', 'pdf', 'both'])->default('xlsx');

            // File paths (relative to storage/app)
            $table->string('file_path_xlsx')->nullable();
            $table->string('file_path_pdf')->nullable();

            $table->enum('status', [
                'queued', 'generating', 'ready', 'failed',
            ])->default('queued');

            $table->text('error_message')->nullable();

            // Customisation overrides (JSON - which sections to include, date ranges, etc.)
            $table->json('config')->nullable();

            $table->decimal('total_amount', 14, 2)->nullable();   // denormalised for listing
            $table->unsignedInteger('record_count')->nullable();

            $table->timestamp('generated_at')->nullable();
            $table->timestamps();

            $table->index(['report_type', 'period']);
            $table->index(['status', 'report_type']);
        });

        // Report schedule configuration
        Schema::create('report_schedules', function (Blueprint $table) {
            $table->id();
            $table->enum('report_type', [
                'monthly_claims_returns', 'capitation_payment_schedule',
                'quarterly_utilisation', 'ffs_claims_register', 'annual_report',
            ]);
            $table->boolean('enabled')->default(true);
            $table->enum('frequency', ['monthly', 'quarterly', 'annually']);
            $table->unsignedTinyInteger('day_of_month')->default(28);  // trigger day
            $table->enum('format', ['xlsx', 'pdf', 'both'])->default('xlsx');
            $table->json('config')->nullable();    // NHIA-specific customisations
            $table->timestamp('last_run_at')->nullable();
            $table->timestamp('next_run_at')->nullable();
            $table->timestamps();
            $table->unique('report_type');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('report_schedules');
        Schema::dropIfExists('generated_reports');
    }
};