<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('enrollees', function (Blueprint $table) {
            $table->id();
            $table->foreignId('branch_id')
                  ->constrained()
                  ->restrictOnDelete();
            $table->foreignId('corporate_id')
                  ->constrained()
                  ->restrictOnDelete();
            
            $table->foreignId('user_id')
                  ->nullable()
                  ->constrained()
                  ->nullOnDelete();
            
            $table->foreignId('plan_id')
                  ->nullable()
                  ->constrained('corporate_plans')
                  ->nullOnDelete();

            // Unique enrollee ID - generated by system e.g. HMO-2024-000001
            $table->string('enrollee_id', 30)->unique();

            $table->string('first_name', 80);
            $table->string('last_name', 80);
            $table->string('middle_name', 80)->nullable();
            $table->date('date_of_birth');
            $table->enum('gender', ['M', 'F']);
            $table->string('phone', 20)->nullable();
            $table->string('email', 150)->nullable();
            $table->text('address')->nullable();
            $table->string('state_of_residence', 50)->nullable();
            $table->string('lga', 80)->nullable();
            $table->string('photo_path')->nullable();
            $table->string('nin', 20)->nullable()->comment('National Identity Number');
            $table->string('staff_id', 50)->nullable()->comment('Corporate employee staff ID');

            // Will be updated after HCPs are created
            $table->unsignedBigInteger('primary_hcp_id')
                  ->nullable()
                  ->comment('Primary care facility (set after HCP migration)');

            $table->enum('status', ['active', 'inactive', 'suspended', 'deceased'])
                  ->default('active');
            $table->date('enrollment_date');
            $table->date('expiry_date');

            $table->decimal('benefit_balance', 15, 2)
                  ->default(0)
                  ->comment('Remaining annual benefit balance in NGN');

            $table->timestamps();
            $table->softDeletes();

            $table->index('branch_id');
            $table->index('corporate_id');
            $table->index('status');
            $table->index('expiry_date');
            $table->index('enrollee_id');
            $table->index(['last_name', 'first_name']);
        });
        
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('enrollees');
    }
};
